### PR TITLE
WIP: proposal for CI-friendly usage with timestamp versions

### PR DESCRIPTION
**Pull request by hohwille**

### CODE REVIEW

**Comment by hohwille** [comment]
> [INFO] Installing /projects/devon/workspaces/main/maven-parent/pom.xml to /Users/hohwille/.m2/repository/com/devonfw/maven-parent/2019.11.15.13.35.00-SNAPSHOT/maven-parent-2019.11.15.13.35.00-SNAPSHOT.pom

While this is fine for releases it is IMHO a problem with SNAPSHOTS during development accross repositories. So IMHO for the latter, we would need a fixed `revision` such as `dev`.
WDYT?

**Comment by vapadwal** [comment]
@hohwille  As discussed earlier I was comparing parent pom with our devon4j parent and below are my findings

- Should we go for Java 11 here instead of <java.version>1.8</java.version>

- license-maven-plugin,  can put this in parent.

- maven-war-plugin is this required in parent pom ?

- In this plugin we have kept failOnError false in devon4j, but this was for security profile

```
       <groupId>org.owasp</groupId>
        <artifactId>dependency-check-maven</artifactId>
        <configuration>
          <failOnError>false</failOnError>
        </configuration>

```

- maven-surefire-plugin we were having 
```
<argLine>-Duser.language=en -Duser.region=EN</argLine>
 ```

- In maven-javadoc-plugin, we  were having javax.interceptor-api as additionalDependency , I think this was because of error javax.interceptor.InterceptorBinding but I am still not sure it is required, might be specific to Java 8
```
<plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-javadoc-plugin</artifactId>
          <version>3.1.0</version>
          <configuration>
            <additionalDependencies>
              <additionalDependency>
                <groupId>javax.interceptor</groupId>
                <artifactId>javax.interceptor-api</artifactId>
                <version>1.2</version>
              </additionalDependency>
            </additionalDependencies>
            <!-- https://issues.apache.org/jira/browse/MJAVADOC-308 -->
            <!-- <notree>true</notree> -->
            <show>private</show>
            <encoding>${project.reporting.outputEncoding}</encoding>
            <charset>${project.build.sourceEncoding}</charset>
            <docfilessubdirs>true</docfilessubdirs>
            <additionalOptions>
              <additionalOption>${javadoc.option.doclint}</additionalOption>
            </additionalOptions>
            <source>8</source>
            <links>
              <link>http://docs.oracle.com/javase/7/docs/api/</link>
              <link>http://m-m-m.sourceforge.net/apidocs/</link>
            </links>
            <doctitle>JavaDocs for ${project.name}</doctitle>
            <windowtitle>JavaDocs for ${project.name}</windowtitle>
          </configuration>
        </plugin>
 ```

**Comment by hohwille** [comment]
@vapadwal thanks for comparing parent POMs and giving this very helpful feedback. I created issue #2 for this in order to track it. There are some findings from you that we need to fix before a first release of this parent pom.

**Comment by hohwille** [comment]
I renamed this to `WIP` as this is just a vision but it does not work as expected.
See also https://issues.apache.org/jira/browse/MNG-624

**Comment by hohwille** [comment]
IMHO a good idea but experiment failed due to maven gaps/bugs/restrictions. So I better close this.

**Pull request closed without merging**
